export const Tripsrows = [
    { id: 1,picture:"../../../images/barcelona.jpg", name: 'Barcelona 3-day Guided Tour', price:"400",city:"Barcelona",country:"Spain",feature:"yes"},
    { id: 2,picture:"../../../images/madrid.jpg", name: 'Madrid Weekend City Break', price:"650",city:"Madrid",country:"Spain",feature:"no"},
    { id: 3,picture:"../../../images/paris.jpg", name: 'Louvre Museum Paris Guided Tour', price:"180",city:"Paris",country:"France",feature:"no"},
    { id: 4,picture:"../../../images/rome.jpg", name: 'Rome Family Holiday, 7 days', price:"200",city:"Rome",country:"Italy",feature:"yes"},
    { id: 5,picture:"../../../images/venice.jpg", name: 'Venice Private Gondola Ride', price:"100",city:"Venice",country:"Italy",feature:"no"},
    { id: 6,picture:"../../../images/frankfurt.jpeg", name: 'Frankfurt on Foot Walking Tour', price:"50",city:"Frankfurt",country:"Germany",feature:"yes"},
    { id: 7,picture:"../../../images/brasov.jpg", name: 'Dracula Castle and Transylvania Day Trip', price:"50",city:"Brasov",country:"Romania",feature:"yes"},
    { id: 8,picture:"../../../images/london.jpg", name: 'Tour of London in a Classic Car', price:"130",city:"London",country:"London",feature:"yes"},

  ];

  export const TripData = [
    {
        id:1,
        title:"Barcelona 3-day Guided Tour",
        city:"Barcelona, Catalonia",
        distance:2500,
        photo:"../../../images/barcelona.jpg",
        address:'Carrer Olot, 24, 08024 Barcelona, Spain',
        price:400,
        featured:true,
        maxGroupSize: 12,
        desc: "This skip-the-line, small-group tour lets you bypass the lines for the most important attractions in Barcelona, so you spend less time waiting and more experiencing the Catalan architect’s genius. Plus, rather than explore independently—and having to arrange travel between the two sites—you get a guide for extra insight and convenient transport laid on. The accomodation is not included in this price.",
    },
    {
        id:2,
        title:"Madrid Weekend City Break",
        city:"Madrid, Spain",
        distance:3200,
        photo:"../../../images/madrid.jpg",
        address:'Calle Gran Vía, 84, Madrid centru, 28013 Madrid, Spania',
        price:650,
        featured:false,
        maxGroupSize: 4,
        desc: "Experience the vibrant culture and rich history of Madrid with a weekend city break! Discover world-famous museums like the Prado and Reina Sofia, explore the bustling streets of the city center, and indulge in delicious Spanish cuisine.Stay in the heart of the action at one of Madrid's many hotels, from boutique options to luxury accommodations. Take advantage of the city's excellent public transportation to visit landmarks like the Royal Palace, Puerta del Sol, and Retiro Park.",
    },
    {
        id:3,
        title:"Louvre Museum Paris Guided Tour",
        city:"Paris, France",
        distance:2300,
        photo:"../../../images/paris.jpg",
        address:'75001 Paris, Franța',
        price:180,
        featured:false,
        maxGroupSize: 2,
        desc: "this is the description",
    },
    {
        id:4,
        title:"Rome Family Holiday, 7 days",
        city:"Rome, Italy",
        distance:2040,
        photo:"../../../images/rome.jpg",
        address:'Via Nazionale 69, Rione Monti, 00184 Roma, Italia',
        price:200,
        featured:true,
        maxGroupSize: 8,
        desc: "Hotel Giolli offers large rooms with Wi-Fi internet access, friendly service and a 24-hour reception. It is located on Via Nazionale, a short walk from Rome's Termini Station.Both the Rome Opera House and the Trevi Fountain are within walking distance of the Giolli. Repubblica Metro Station is 200 meters away.The rooms of Hotel Giolli are quiet and equipped with air conditioning, satellite TV, hairdryer and minibar. The floors are eco-friendly wooden parquet, and some rooms have balconies overlooking the main street.Breakfast is served in the panoramic dining room. The hotel also has a bar and a comfortable lounge. Staff can arrange airport transfers and book museum tickets.",
    },
    {
        id:5,
        title:"Venice Private Gondola Ride",
        city:"Venice, Italy",
        distance:1300,
        photo:"../../../images/venice.jpg",
        address:'Campo San Moisè, 30124 Venezia VE, Italy',
        price:100,
        featured:false,
        maxGroupSize:6,
        desc: 'There is no more memorable way to explore Venice than by traditional gondola, but most standard rides last just 30 minutes. This exclusive 45-minute experience gives you enough time to glide past famous sights like the Rialto Bridge and Grand Canal and also float through quiet, lesser-known neighborhoods. Set off from near St. Mark’s Square with a true “gondoliere” and savor Venice from its historic canals' ,
    },
    {
        id:6,
        title:"Frankfurt on Foot Walking Tour",
        city:"Frankfurt, Germany",
        distance:1600,
        photo:"../../../images/frankfurt.jpeg",
        address:'Braubachstraße 41, 60311 Frankfurt am Main, Germany',
        price:50,
        featured:true,
        maxGroupSize: 12,
        desc: "Maximize your time in Frankfurt, and see the city on a guided tour by foot. Visiting the places where the tour buses can't reach, you'll get up close to the standout landmarks, find the most impressive photo points, and hear Frankfurt's history told through engaging commentary. The Old Opera House, Roemerberg, and Frankfurt Cathedral are among the highlights.",
    },
    {
        id:7,
        title:"Dracula's Castle and Transylvania Day Trip",
        city:"Brasov, Romania",
        distance:100,
        photo:"../../../images/brasov.jpg",
        address:'Piața Romană, București, Romania',
        price:50,
        featured:true,
        maxGroupSize: 20,
        desc: "Explore Transylvania and skip the lines at Bran Castle with a guide on this full-day tour from Bucharest. Hotel pickup and drop-off in an air-conditioned minivan make your trip easy and comfortable. Visit Peles Castle and explore the museum’s collection. Stop at Bran Castle and take a tour of Brasov City. View Brasov’s medieval fortress and Weaver’s Bastion before returning to Bucharest.",
    },
    {
        id:8,
        title:"Tour of London in a Classic Car",
        city:"London, United Kingdom",
        distance:2400,
        photo:"../../../images/london.jpg",
        address:'Zetter Townhouse Clerkenwell, 49-50 St John Sq, London EC1V 4JJ, UK',
        price:130,
        featured:true,
        maxGroupSize: 4,
        desc: "See London with your own private driver who shows you around the city in a classic Mini Cooper. During your two-hour tour, your driver-guide shows you both top attractions including St Paul's Cathedral, Houses of Parliament (aka Palace of Westminster) and Big Ben, and lesser-known favorites such as Borough Market — the oldest food market in London. Get an insider’s perspective on the best places to go in London and enjoy the fun of seeing the city in your own private car.",
    }
]